analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    #- avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    #- avoid_return_types_on_setters
    - camel_case_types
    - constant_identifier_names
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_duplicate_case_values
    #- non_constant_identifier_names
    #- prefer_final_fields
    #- unnecessary_new
    - super_goes_last
    #- type_init_formals
    - unnecessary_brace_in_string_interps
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
